name: cargobump123
on:
  workflow_dispatch: {}
  push:
    tags:
      - v*

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version
        if: always()  # Ensure it runs even if manually triggered
        uses: tj-actions/cargo-bump@v3.0.2
