name: cargobump
on:
  push:
    tags:
      - v*

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version
        uses: tj-actions/cargo-bump@v3
      # Commit and Push changes to the Cargo.toml
