name: Check Cargo.toml for latest stable edition and rust-version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
  workflow_dispatch: {}
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          rust-version: stable

      - name: Fetch latest stable Rust version
        run: |
          latest_stable_rust=$(rustup show active-toolchain | grep 'stable' | awk '{print $2}')
          echo "Latest stable Rust version: $latest_stable_rust"
          echo "LATEST_RUST_VERSION=$latest_stable_rust" >> $GITHUB_ENV

      - name: Check Cargo.toml for edition and rust-version updates
        run: |
          edition=$(grep '^edition' Cargo.toml | cut -d '=' -f2 | tr -d '[:space:]')
          rust_version=$(grep '^rust-version' Cargo.toml | cut -d '=' -f2 | tr -d '[:space:]')

          echo "Edition: $edition"
          echo "Rust Version: $rust_version"

          # Check that the edition is up-to-date (currently 2024)
          if [ "$edition" != "2024" ]; then
            echo "Edition is not 2024. Please update it."
            exit 1
          fi

          # Check that the rust-version is the latest stable version
          if [ "$rust_version" != "$LATEST_RUST_VERSION" ]; then
            echo "Rust version is not the latest stable version ($LATEST_RUST_VERSION). Please update it."
            exit 1
          fi
