name: Updatecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write

jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v5

      - name: Install stable Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Update Cargo.lock
        run: cargo update --verbose

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

  codeql_scan:
    name: CodeQL Security Scan
    needs: latest_deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4.30.8
        with:
          languages: rust

      - name: Autobuild
        uses: github/codeql-action/autobuild@v4.30.8

      - name: Analyze and upload results
        uses: github/codeql-action/analyze@v4.30.8
        with:
          output: codeql-results.sarif
          upload: true

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: sarif-report
          path: codeql-results.sarif
