name: Updatecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: write
  security-events: write

jobs:
  latest_deps:
    name: Latest Dependencies
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      CARGO_RESOLVER_INCOMPATIBLE_RUST_VERSIONS: allow
    steps:
      - uses: actions/checkout@v5

      - name: Install stable Rust
        run: |
          rustup update stable
          rustup default stable

      - name: Fix
        run: cargo fix --edition --edition-idioms --verbose

      - name: Update Cargo.lock
        run: cargo update --verbose    

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
